# Generated by Django 4.2.2 on 2023-06-05 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0002_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="rate",
            name="by",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates_given",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
