# Generated by Django 4.2.2 on 2023-06-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0003_rate_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hero",
            options={"ordering": ("name",)},
        ),
        migrations.AlterField(
            model_name="hero",
            name="name",
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="hero",
            name="power",
            field=models.TextField(db_index=True),
        ),
    ]
